### ISSUE TITLE
What are you fixing ??

### ISSUE THREAD

**Issue by DragonfireHD** [Deepslate/MapImageEngine#1]
In the Code gives not the Fail coding

![Screenshot_20210706-011730_ES File Explorer](https://user-images.githubusercontent.com/50929188/124521385-f9a60600-ddf7-11eb-9fb2-39c37a19f6ba.jpg)

**Comment by michoudll** [comment]
fixes are currently working with the latest pmmp 3.x.y.
![Imgur](https://imgur.com/6MQbUug)
